model_config:
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
  cache_dir: /home/violet/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct/
  #/scr/ziyxiang/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-8B-Instruct/
  #/scr/jphilipp/stargate/pretrained_models/Meta-Llama-3.1-8B-Instruct

tokenizer_config:
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
  cache_dir: /home/violet/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B-Instruct/
  #/scr/ziyxiang/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3-8B-Instruct/
  #/scr/jphilipp/stargate/pretrained_models/Meta-Llama-3.1-8B-Instruct
  model_max_length: 2048

wandb:
  project: tool-reasoning
  name: prm_small

data: data/numina_small.json
test_split: 0.05

training_args:
  output_dir: /home/violet/tools/checkpoints/prm_small
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 128
  learning_rate: 1e-5
  num_train_epochs: 2
  save_total_limit: 4
  # do_eval: false
  seed: 42
  save_strategy: steps
  save_steps: 20
  evaluation_strategy: steps
  eval_steps: 10
  lr_scheduler_type: linear
  warmup_steps: 20
  bf16: true
  logging_steps: 1
  logging_strategy: steps
  report_to: wandb